apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: reliability
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: YOUR_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-api:v5
          envFrom:
            - configMapRef:
                name: platform-config
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
