#!/bin/bash
set -e

# These values come from environment variables or script arguments
INCIDENT_ID=${1:-'INC-UNKNOWN'}
SERVICE=${2:-'unknown-service'}
START_TIME=${3:-'unknown'}
END_TIME=${4:-$(date -u '+%Y-%m-%dT%H:%M:%SZ')}
ROOT_CAUSE=${5:-'Under investigation'}
FIX_APPLIED=${6:-'Manual remediation'}
PREVENTION=${7:-'Review deployment process'}

# Calculate duration if both times are provided
DURATION='unknown'
if [ "$START_TIME" != 'unknown' ]; then
  START_EPOCH=$(date -d "$START_TIME" +%s 2>/dev/null || date -j -f '%Y-%m-%dT%H:%M:%SZ' "$START_TIME" +%s 2>/dev/null || echo 0)
  END_EPOCH=$(date +%s)
  if [ "$START_EPOCH" -gt 0 ]; then
    DIFF_MINS=$(( (END_EPOCH - START_EPOCH) / 60 ))
    DURATION="${DIFF_MINS} minutes"
  fi
fi

POSTMORTEM_TEXT=$(cat <<TXT
=== POSTMORTEM: ${INCIDENT_ID} ===

Service Affected: ${SERVICE}
Started: ${START_TIME}
Recovered: ${END_TIME}
Duration: ${DURATION}

WHAT HAPPENED
${SERVICE} experienced a degradation starting at ${START_TIME}.

ROOT CAUSE
${ROOT_CAUSE}

WHAT FIXED IT
${FIX_APPLIED}

PREVENTION
${PREVENTION}

GENERATED BY: Reliability Platform V9 Automated Postmortem
TXT
)

echo "$POSTMORTEM_TEXT"

# Post to Slack
if [ -n "$SLACK_WEBHOOK_URL" ]; then
  ./incident/slack_alert.sh RESOLVED \
    "Postmortem: ${INCIDENT_ID}" \
    "${POSTMORTEM_TEXT}" \
    "${SERVICE}"
fi

echo "Postmortem complete for ${INCIDENT_ID}"
